import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Socail Pilot",
  description: "Generated by create next app",
  icons: [{ rel: 'icon', url: '/favicon.png' }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
